<a href="https://colab.research.google.com/github/shironoirL/3.10train/blob/main/drugbank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
from google.colab import drive

drive.mount('/content/gdrive/', force_remount=True)
data_table.enable_dataframe_formatter()

Mounted at /content/gdrive/

In [45]:
import pandas as pd
pd.set_option('display.max_columns', None)
from google.colab import data_table

In [46]:
gdrive_path = '/content/gdrive/My Drive/drugbank/'

In [75]:
drugbank = pd.read_csv(f'{gdrive_path}drugbank.tsv',sep = '\t')
proteins = pd.read_csv(f'{gdrive_path}proteins.tsv', sep = '\t')
gwas_catalog = pd.read_csv(f'{gdrive_path}gwas_catalog.tsv', sep= '\t', low_memory=False)

In [76]:
drugbank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7759 entries, 0 to 7758
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   drugbank_id  7759 non-null   object
 1   name         7759 non-null   object
 2   type         7759 non-null   object
 3   groups       7759 non-null   object
 4   atc_codes    1480 non-null   object
 5   categories   1698 non-null   object
 6   inchikey     6810 non-null   object
 7   inchi        6810 non-null   object
 8   description  3073 non-null   object
dtypes: object(9)
memory usage: 545.7+ KB

In [77]:
proteins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19906 entries, 0 to 19905
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   drugbank_id     19906 non-null  object
 1   category        19906 non-null  object
 2   uniprot_id      19906 non-null  object
 3   entrez_gene_id  19906 non-null  int64
 4   organism        19906 non-null  object
 5   known_action    19906 non-null  object
 6   actions         10302 non-null  object
 7   pubmed_ids      18173 non-null  object
dtypes: int64(1), object(7)
memory usage: 1.2+ MB

In [78]:
gwas_catalog.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470406 entries, 0 to 470405
Data columns (total 34 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   DATE ADDED TO CATALOG       470406 non-null  object
 1   PUBMEDID                    470406 non-null  int64
 2   FIRST AUTHOR                470406 non-null  object
 3   DATE                        470406 non-null  object
 4   JOURNAL                     470406 non-null  object
 5   LINK                        470406 non-null  object
 6   STUDY                       470406 non-null  object
 7   DISEASE/TRAIT               470406 non-null  object
 8   INITIAL SAMPLE SIZE         470405 non-null  object
 9   REPLICATION SAMPLE SIZE     67919 non-null   object
 10  REGION                      448623 non-null  object
 11  CHR_ID                      448633 non-null  object
 12  CHR_POS                     448633 non-null  object
 13  REPORTED GENE(S)            265152 non-null  object
 14  MAPPED_GENE                 439157 non-null  object
 15  UPSTREAM_GENE_ID            133144 non-null  object
 16  DOWNSTREAM_GENE_ID          133938 non-null  object
 17  SNP_GENE_IDS                289051 non-null  object
 18  UPSTREAM_GENE_DISTANCE      133144 non-null  float64
 19  DOWNSTREAM_GENE_DISTANCE    133938 non-null  float64
 20  STRONGEST SNP-RISK ALLELE   470406 non-null  object
 21  SNPS                        470406 non-null  object
 22  MERGED                      470391 non-null  float64
 23  SNP_ID_CURRENT              445549 non-null  object
 24  CONTEXT                     449119 non-null  object
 25  INTERGENIC                  465162 non-null  float64
 26  RISK ALLELE FREQUENCY       453602 non-null  object
 27  P-VALUE                     470406 non-null  float64
 28  PVALUE_MLOG                 470406 non-null  float64
 29  P-VALUE (TEXT)              66175 non-null   object
 30  OR or BETA                  398743 non-null  float64
 31  95% CI (TEXT)               392140 non-null  object
 32  PLATFORM [SNPS PASSING QC]  470406 non-null  object
 33  CNV                         470406 non-null  object
dtypes: float64(7), int64(1), object(26)
memory usage: 122.0+ MB

# **File headers for catalog version 1.0**
DATE ADDED TO CATALOG* +: Date a study is published in the catalog

PUBMEDID* +: PubMed identification number

FIRST AUTHOR* +: Last name and initials of first author

DATE* +: Publication date (online (epub) date if available)

JOURNAL* +: Abbreviated journal name

LINK* +: PubMed URL

STUDY* +: Title of paper

DISEASE/TRAIT* +: Disease or trait examined in study

INITIAL SAMPLE DESCRIPTION* +: Sample size and ancestry description for stage 1 of GWAS (summing across multiple Stage 1 populations, if applicable)

REPLICATION SAMPLE DESCRIPTION* +: Sample size and ancestry description for subsequent replication(s) (summing across multiple populations, if applicable)

REGION*: Cytogenetic region associated with rs number

CHR_ID*: Chromosome number associated with rs number

CHR_POS*: Chromosomal position associated with rs number

REPORTED GENE(S)*: Gene(s) reported by author

MAPPED GENE(S)*: Gene(s) mapped to the strongest SNP. If the SNP is located within a gene, that gene is listed. If the SNP is located within multiple genes, these genes are listed separated by commas. If the SNP is intergenic, the upstream and downstream genes are listed, separated by a hyphen.

UPSTREAM_GENE_ID*: Entrez Gene ID for nearest upstream gene to rs number, if not within gene

DOWNSTREAM_GENE_ID*: Entrez Gene ID for nearest downstream gene to rs number, if not within gene

SNP_GENE_IDS*: Entrez Gene ID, if rs number within gene; multiple genes denotes overlapping transcripts

UPSTREAM_GENE_DISTANCE*: distance in kb for nearest upstream gene to rs number, if not within gene

DOWNSTREAM_GENE_DISTANCE*: distance in kb for nearest downstream gene to rs number, if not within gene

STRONGEST SNP-RISK ALLELE*: SNP(s) most strongly associated with trait + risk allele (? for unknown risk allele). May also refer to a haplotype.

SNPS*: Strongest SNP; if a haplotype it may include more than one rs number (multiple SNPs comprising the haplotype)

MERGED*: denotes whether the SNP has been merged into a subsequent rs record (0 = no; 1 = yes;)

SNP_ID_CURRENT*: current rs number (will differ from strongest SNP when merged = 1)

CONTEXT*: provides information on a variant’s predicted most severe functional effect from Ensembl

INTERGENIC*: denotes whether SNP is in intergenic region (0 = no; 1 = yes)

RISK ALLELE FREQUENCY*: Reported risk/effect allele frequency associated with strongest SNP in controls (if not available among all controls, among the control group with the largest sample size). If the associated locus is a haplotype the haplotype frequency will be extracted.

P-VALUE*: Reported p-value for strongest SNP risk allele (linked to dbGaP Association Browser). Note that p-values are rounded to 1 significant digit (for example, a published p-value of 4.8 x 10-7 is rounded to 5 x 10-7).

PVALUE_MLOG*: -log(p-value)

P-VALUE (TEXT)*: Information describing context of p-value (e.g. females, smokers).

OR or BETA*: Reported odds ratio or beta-coefficient associated with strongest SNP risk allele. Note that if an OR <1 is reported this is inverted, along with the reported allele, so that all ORs included in the Catalog are >1. Appropriate unit and increase/decrease are included for beta coefficients.

95% CI (TEXT)*: Reported 95% confidence interval associated with strongest SNP risk allele, along with unit in the case of beta-coefficients. If 95% CIs are not published, we estimate these using the standard error, where available.

PLATFORM (SNPS PASSING QC)*: Genotyping platform manufacturer used in Stage 1; also includes notation of pooled DNA study design or imputation of SNPs, where applicable

CNV*: Study of copy number variation (yes/no)

ASSOCIATION COUNT+: Number of associations identified for this study

In [81]:
drugbank.sample(5)

,drugbank_id,name,type,groups,atc_codes,categories,inchikey,inchi,description
4963,DB05183,MLN0415,small molecule,investigational,NaN,NaN,NaN,NaN,"MLN0415 is a novel, small molecule IKK2 inhibi..."
3595,DB03754,Tris(Hydroxymethyl)Aminomethane,small molecule,experimental,NaN,Buffers,InChIKey=LENZDBCJOHFCAS-UHFFFAOYSA-O,"InChI=1S/C4H11NO3/c5-4(1-6,2-7)3-8/h6-8H,1-3,5...",An organic amine proton acceptor. It is used i...
5158,DB05396,albumin-interferon alpha,small molecule,investigational,NaN,NaN,NaN,NaN,Albumin-interferon alpha (Albuferon) is a nove...
5339,DB05775,CRx-401,small molecule,investigational,NaN,NaN,NaN,NaN,CRx-401 is a novel insulin sensitizer designed...
7623,DB08881,Vemurafenib,small molecule,approved,L01XE15,NaN,InChIKey=GPXBXXGIAQBQNI-UHFFFAOYSA-N,"InChI=1S/C23H18ClF2N3O3S/c1-2-9-33(31,32)29-19...",Vemurafenib is a BRAF enzyme inhibitor develop...

In [82]:
proteins.sample(5)

,drugbank_id,category,uniprot_id,entrez_gene_id,organism,known_action,actions,pubmed_ids
8290,DB00830,target,Q01959,6531,Human,yes,inhibitor,17139284|17016423|12106802|17017961
7789,DB08339,target,P00519,25,Human,unknown,NaN,10592235
14214,DB08743,target,P27487,1803,Human,unknown,NaN,10592235
13027,DB00622,target,P62158,808,Human,unknown,other/unknown,6865927
3813,DB08911,enzyme,P10632,1558,Human,unknown,inhibitor,NaN

In [83]:
gwas_catalog.sample(5)

Warning: Total number of columns (34) exceeds max_columns (20). Falling back to pandas display.

,DATE ADDED TO CATALOG,PUBMEDID,FIRST AUTHOR,DATE,JOURNAL,LINK,STUDY,DISEASE/TRAIT,INITIAL SAMPLE SIZE,REPLICATION SAMPLE SIZE,REGION,CHR_ID,CHR_POS,REPORTED GENE(S),MAPPED_GENE,UPSTREAM_GENE_ID,DOWNSTREAM_GENE_ID,SNP_GENE_IDS,UPSTREAM_GENE_DISTANCE,DOWNSTREAM_GENE_DISTANCE,STRONGEST SNP-RISK ALLELE,SNPS,MERGED,SNP_ID_CURRENT,CONTEXT,INTERGENIC,RISK ALLELE FREQUENCY,P-VALUE,PVALUE_MLOG,P-VALUE (TEXT),OR or BETA,95% CI (TEXT),PLATFORM [SNPS PASSING QC],CNV
384362,2022-04-27,35213538,Richardson TG,2022-02-25,PLoS Biol,www.ncbi.nlm.nih.gov/pubmed/35213538,Characterising metabolomic signatures of lipid...,Cholesterol levels in very large HDL,"115,082 European ancestry individuals",NaN,2p21,2,43828371,NaN,ABCG5,NaN,NaN,ENSG00000138075,NaN,NaN,rs114938914-C,rs114938914,0.0,114938914,non_coding_transcript_exon_variant,0.0,0.938588,7.000000e-10,9.154902,NaN,0.048091,[0.033-0.063] unit increase,NR [11722792] (imputed),N
166851,2018-11-16,30072576,Emilsson V,2018-08-02,Science,www.ncbi.nlm.nih.gov/pubmed/30072576,Co-regulatory networks of human serum proteins...,Blood protein levels,"3,200 European ancestry individuals",NaN,1q21.3,1,154454494,IL6R,IL6R,NaN,NaN,ENSG00000160712,NaN,NaN,rs2228145-A,rs2228145,0.0,2228145,missense_variant,0.0,0.5828125,0.000000e+00,449.096910,"(IL6R, 4139_71_2)",0.992696,[0.96-1.03] unit decrease,Illumina [> 1000000] (imputed),N
455334,2021-08-24,34021172,Christakoudi S,2021-05-21,Sci Rep,www.ncbi.nlm.nih.gov/pubmed/34021172,GWAS of allometric body-shape indices in UK Bi...,Waist-hip index,"219,872 British ancestry women",NaN,12q24.31,12,124092631,FAM101A,RFLNA,NaN,NaN,ENSG00000178882,NaN,NaN,rs372527826-A,rs372527826,0.0,372527826,intron_variant,0.0,NR,3.000000e-14,13.522879,NaN,0.030531,[0.023-0.038] unit decrease,Affymetrix [319769] (imputed),N
228578,2020-07-28,32450446,Wang H,2020-04-29,Neurobiol Aging,www.ncbi.nlm.nih.gov/pubmed/32450446,Genome-wide interaction analysis of pathologic...,Neurofibrillary tangles (SNP x SNP interaction),"1,316 individuals",NaN,4q28.3,4,130200237,NR x NR,No mapped genes x WDR1 - N/A,NaN,NaN,NaN,NaN,NaN,rs7374138-? x rs13141189-?,rs7374138 x rs13141189,0.0,NaN,intron_variant x intergenic_variant,NaN,NR,7.000000e-08,7.154902,NaN,NaN,NaN,"Affymetrix, Illumina [279409] (imputed)",N
188019,2018-12-03,30348214,Zhang Q,2018-10-22,Genome Med,www.ncbi.nlm.nih.gov/pubmed/30348214,Genotype effects contribute to variation in lo...,DNA methylation variation (age effect),Up to 954 individuals,NaN,1q23.1,1,157869964,NR,CD5L,NaN,NaN,ENSG00000073754,NaN,NaN,rs114458961-?,rs114458961,0.0,114458961,intron_variant,0.0,NR,3.000000e-08,7.522879,NaN,NaN,NaN,Illumina [7760689] (imputed),N

In [92]:
proteins.loc[proteins['drugbank_id'] == 'DB05183']

,drugbank_id,category,uniprot_id,entrez_gene_id,organism,known_action,actions,pubmed_ids
10867,DB05183,target,O14920,3551,Human,unknown,NaN,NaN

In [87]:
drugbank['drugbank_id'].sample(1)

3587    DB03746
Name: drugbank_id, dtype: object

In [71]:
drugbank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7759 entries, 0 to 7758
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   drugbank_id  7759 non-null   object
 1   name         7759 non-null   object
 2   type         7759 non-null   object
 3   groups       7759 non-null   object
 4   atc_codes    1480 non-null   object
 5   categories   1698 non-null   object
 6   inchikey     6810 non-null   object
 7   inchi        6810 non-null   object
 8   description  3073 non-null   object
dtypes: object(9)
memory usage: 545.7+ KB